name: unreel
description: Find out which movie to watch tonight.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  after_layout: ^1.0.7+2
  cupertino_icons: ^0.1.2
  fading_edge_scrollview: ^1.0.2
  http: ^0.12.0+2
  provider: ^3.1.0
  intl: ^0.16.0
  sqflite: ^1.1.7+1
  path: ^1.6.4
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
